[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = ["cd backend && npm run build && mkdir -p data"]

[start]
cmd = "cd backend && node dist/index.js"
